### ISSUE TITLE
[Enhancement] Revamp the UI

### ISSUE THREAD

**Issue by prakhartiwari0** [mywebshortcuts/mywebshortcuts#29]
### What needs to be enhanced?
The current UI is not up to the mark and needs a lot of improvements. 

### Solution
In a Discussion (https://github.com/prakhartiwari0/my-web-shortcuts/discussions/25#discussioncomment-7348759), @beingsie created a mockup UI for this extension. It does need some changes, but the overall UI is pretty good. I'm planning to implement it for the Alpha v1.0.0.

**Comment by beingsie** [comment]
> @beingsie Please tell me if you're available and willing to implement this UI. I will assign you this issue and we will discuss what changes need to be made. If you can't do it, I will try to implement it myself which you can improve later on.

Hi @prakhartiwari0!
- Thank you for considering my suggestions for the new UI features and improvements!
- I believe it would be more efficient if you initiated the development, given your in-depth knowledge of the project. I'm more than willing to provide support and work on the improvements afterward to ensure the best results.

**Comment by prakhartiwari0** [comment]
@beingsie Share your thoughts on the new element selector UI. Earlier it was very big and had the options in it, but now I have moved the option to key selector dialog as it makes more sense there + the element selector should be small for better User experience, as I would not like that big popup on a webpage while selecting an element.

**Comment by prakhartiwari0** [comment]
@beingsie Check the latest PR #35, I have done major UI changes. Test it yourself and share feedback :)

**Comment by beingsie** [comment]
PR's #38 and #39 are awesome additions to the extension! These enhancements give it new features and functionality! Great work @prakhartiwari0, I believe this should close this issue for now as it's met the goal, further UI changes can be introduced in later updates, love your work!
- P.S. Animations are cool!

**Comment by prakhartiwari0** [comment]
The final major changes has been made in this commit: https://github.com/mywebshortcuts/mywebshortcuts/commit/89608f4b49532a2cf57a18e1ace8e9cc33819881
